steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'postgres-appliance'
  args:
  - build
  - --build-arg
  - WITH_PERL=false
  - --build-arg
  - COMPRESS=true
  - --build-arg
  - DEMO=false
  - --build-arg
  - PGVERSION=12
  - --build-arg
  - PGOLDVERSIONS="9.6 11"
  - --tag
  - eu.gcr.io/$_PROJECT_ID/$_REPO_NAME:$_REVISION_ID
  - --tag
  - eu.gcr.io/$_PROJECT_ID/$_REPO_NAME:latest
  - --file
  - Dockerfile
  - --no-cache
  - .
  timeout: 1800s
images:
- 'eu.gcr.io/$_PROJECT_ID/$_REPO_NAME:$_REVISION_ID'
- 'eu.gcr.io/$_PROJECT_ID/$_REPO_NAME:latest'
timeout: 2100s
