steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'postgres-appliance'
  args:
    - build
    - --build-arg
    - COMPRESS=false
    - --build-arg
    - PGVERSION=12
    - --tag
    - gcr.io/$_PROJECT_ID/$_REPO_NAME:$_REVISION_ID
    - --tag
    - gcr.io/$_PROJECT_ID/$_REPO_NAME:latest
    - --file
    - Dockerfile
    - --no-cache
    - .
  timeout: 1800s
images:
  - 'gcr.io/$_PROJECT_ID/$_REPO_NAME:$_REVISION_ID'
  - 'gcr.io/$_PROJECT_ID/$_REPO_NAME:latest'
timeout: 1800s
